### ISSUE TITLE
Instant Crash when opening settings via Modmenu (1.17.1)

### ISSUE THREAD

**Issue by i-like-trains72** [TeamMidnightDust/CullLeaves#12]
Using latest Cull Leaves and Mod Menu and Fabric API for 1.17
I crash whenever I go into Mods > Cull Leaves > Settings Icon
[crash.txt](https://github.com/TeamMidnightDust/CullLeaves/files/7024159/crash.txt)

Mapped the crash for your convenience: 
[mapped crash.txt](https://github.com/TeamMidnightDust/CullLeaves/files/7024163/mapped.crash.txt)

No crashes without Modmenu.

**Comment by Motschen** [comment]
Fixed in 2.3.0
