### ISSUE TITLE
[bug] Some faces are culled at some times when they shouldn't be with Smart Leaves

### ISSUE THREAD

**Issue by triphora** [TeamMidnightDust/CullLeaves#15]
When at a certain distance away from any leaves, some faces get culled when they shouldn't be. This is a very vague explanation, so here's a video demonstration:
https://qu.ax/i2Y.webm
fwiw, this is with Iris 1.1.2 with a Sodium 0.3.2 derivative, but I've observed this across both 1.17 and 1.16, over several Sodium versions (stable and unstable). It occurs with no additional resource pack as well. I've been able to live with this but it's gotten really annoying recently for whatever reason.
This only occurs when Smart Leaves is enabled.

**Comment by Altirix** [comment]
#11

https://github.com/CaffeineMC/sodium-fabric/issues/817 

disable block face culling. is the workaround but it is a performance hit
