### ISSUE TITLE
Not working (sorry not very descriptive)

### ISSUE THREAD

**Issue by xanthian** [TeamMidnightDust/CullLeaves#16]
Not sure this is working for me, unless im missing something???
I have a datapack on my server that has fast leaf decay, which I presumed may be interfering, however, same issue in SP without this datapack.

I've removed all mods apart from latest fabricapi and this mod also removed all resource packs
Any pointers I could be looking for that may be causing the interference
MC1.17.1

![Screenshot 2021-10-22 134835](https://user-images.githubusercontent.com/7688001/138458981-a160de14-0eea-4fb3-b9aa-dc0cc4981733.png)
Screenie was taken with mods, couldnt be bothered to take another :)
same effect regardless

**Comment by Motschen** [comment]
It's working, but it will only look like the OptiFine smart leaves on fancy graphics.
It also improves FPS on fast graphics, it will just have no visual impact.
