### ISSUE TITLE
CullLeaves causes the player to have an unremovable Witch hat

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [TeamMidnightDust/CullLeaves#17]
**MC** 1.17.1
**Fabric** loader 0.12.3; API 0.41.0
**CullLeaves** 2.3.1

All of a sudden 2 mods in my modpack started to cause this weird bug, 1 is CullLeaves, another [Cool Elytra Roll](https://www.curseforge.com/minecraft/mc-mods/cool-elytra-roll). Tested with only fabric API and CullLeaves loaded.

To reproduce:

1. Install fabric loader and API
2. Launch the game, create a new world or join an old one
3. Look at your character in 3rd person or in the inventory - everything is normal
4. Close the game, install CullLeaves, start the game again
5. Enter the same world or create a new one and look at your character - now it has a witch hat

**Screenshots:**

Vanilla
![2021-10-30_14 08 46](https://user-images.githubusercontent.com/86702831/139532940-71b64f30-ad31-4526-9cba-db5bab6a9516.png)

With CullLeaves installed
![2021-10-30_14 10 34](https://user-images.githubusercontent.com/86702831/139532946-534a3f14-14b2-407a-9189-0c2ce060d3f7.png)

Logs:

- Vanilla: https://gist.github.com/Footage2-Amply-Pounce/6343b3c2d87bd2df52a17583c8291a43
- With CullLeaves: https://gist.github.com/Footage2-Amply-Pounce/981a6caaa60df2c2789e1142223940b8

**Comment by Motschen** [comment]
That's not a weird bug, it's intended behavior during halloween.
You can disable it in the MidnightLib config.
This feature was removed in more recent versions of MidnightLib, but most of my mods still ship an older version.

**Comment by Footage2-Amply-Pounce** [comment]
Ohhhh.. I spent an embarrassing amount of time finding out which mods caused this 😂 Thanks for telling me.
