### ISSUE TITLE
Possible visual improvment

### ISSUE THREAD

**Issue by Elliad-Live** [TeamMidnightDust/CullLeaves#2]
Would it be possible to, instead of 'hiding' or 'culling' the inner leaves (not really sure what the correct term is) instead turn the inner leaf blocks into the non-transparent version? 

My thought process is that the trees with culled leaves look very sparse, and this change would just make them keep the sort of thickness that vanilla fancy leaves has without as much of a performance hit.

**Comment by Motschen** [comment]
Is that what you mean:
![2021-01-14_15 32 56](https://user-images.githubusercontent.com/49783724/104604865-1b5ed580-567e-11eb-9244-728b81e064df.png)

**Comment by Motschen** [comment]
If yes then try this resouecepack: 
[Smart-Leaves-1.0-§31.16+§o.zip](https://github.com/TeamMidnightDust/CullLeaves/files/5815058/Smart-Leaves-1.0-.31.16%2B.o.zip)

**Comment by Motschen** [comment]
Officially dded in Cull Leaves 2.0.0
