### ISSUE TITLE
Weird visual glitch with leaves?

### ISSUE THREAD

**Issue by Scarlaid** [TeamMidnightDust/CullLeaves#21]
Apparently looking at the leaves from certain distance give this:
Is this the problem with the mod or the outdated texture pack, or something else?
![image](https://user-images.githubusercontent.com/90851437/154827257-2d1dbc4b-c539-4ef1-a149-c890239ba46d.png)

**Comment by Scarlaid** [comment]
With near view distance:
![image](https://user-images.githubusercontent.com/90851437/154827305-af983fa3-5033-4f78-9026-e7e3d02efb47.png)

**Comment by TheRealDadbeard** [comment]
I have a similar issue. You can see when the leaves becomes nicer when the resource pack is activated as it only works wehn you're pretty close.

**Comment by Scarlaid** [comment]
Yep, Motschen was right, disabling "Use Block Face Culling" fixed the problem
Should have look around the settings first
![image](https://user-images.githubusercontent.com/90851437/161362490-175f6b28-801d-45c2-9191-71e52f5d3dfe.png)
