### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by IonhXD** [TeamMidnightDust/CullLeaves#27]
Cullleaves isn't doing anything and its still the same

**Comment by IonhXD** [comment]
Yo how can I fix it

**Comment by IonhXD** [comment]
like I have the mod and its also in my packs and I have it on so idk why it isn't working

**Comment by Motschen** [comment]
Keep in mind that it doesn't change the visuals in Fast Graphics or when using my Better Leaves pack, but the performance is still drastically increased.
