### ISSUE TITLE
Question about Sodium

### ISSUE THREAD

**Issue by assasin541** [TeamMidnightDust/CullLeaves#3]
Do i have to have enabled graphics to fancy? Because otherwise it doesn't work.
Is this how it should look? https://share.getcloudapp.com/v1u47nyl

**Comment by Motschen** [comment]
Yes, that's how it's supposed to look.
The mod also has an effect on fast graphics, because for some reason minecraft doesn't cull the leaves even when they're set to fast.

**Comment by assasin541** [comment]
@Motschen I don't see the difference on fast graphics.

**Comment by Motschen** [comment]
Well, you only see it when you fly into the leaves of a tree in spectator mode

**Comment by assasin541** [comment]
@Motschen is this the final effect? Soidum fancy graphics + your resourcepack. https://share.getcloudapp.com/6quxgKyb

**Comment by assasin541** [comment]
@Motschen why they don't work sometimes? They have black/broken parts.

**Comment by Motschen** [comment]
yeah, minecraft isn't that good at handling models bigger than one block, so there are some rare problems like broken lighting.
Sadly I don't think it's fixable for me

**Comment by JamesTheAwesomeDude** [comment]
> Do i have to have enabled graphics to fancy? Because otherwise it doesn't work.

Depending on how [sodium-fabric#233](https://github.com/jellysquid3/sodium-fabric/issues/233#issuecomment-761610921) is resolved, this may be fixable in the near future.

I would appreciate it if Cull Leaves jumped in and added the ability to force Fancy leaves on Fast graphics, but that would be above-and-beyond and probably out-of-scope.
