### ISSUE TITLE
Crashing in Better End biomes containing trees

### ISSUE THREAD

**Issue by purejosh** [TeamMidnightDust/CullLeaves#31]
Here's the crash log I'm getting, but please ping me if you need any more info. 

I'm unsure which biome it is, the one I was nearest is called Nightshade Redwoods. 

https://gist.github.com/purejosh/2072281475ceb410332df7447e5a0da6

**Comment by Motschen** [comment]
See if disabling the Sodium fix in CullLeaves' config fixes it.
