### ISSUE TITLE
Incompatible with Enhanced Block Entities

### ISSUE THREAD

**Issue by pityalvarez** [TeamMidnightDust/CullLeaves#32]
I'm pretty sure I can't get these two to work together, just for others to keep in mind. Both of these mods are always included in "optimization mods" videos.

**Comment by Motschen** [comment]
They work perfectly together for me, I use both all the time.
What makes you think otherwise?

**Comment by pityalvarez** [comment]
Sorry, I'm using 2.1.0 the one that is 50kb instead of 500kb, and i disabled every other mod, and it just doesn't work, any possible reason? I checked the version correctly

**Comment by Motschen** [comment]
So this one: https://modrinth.com/mod/cull-leaves/version/2.1.0
That is actually quite old and not supported anymore, though I see no reason why it shouldn't work with EBE.
Is there a crash log or something?

**Comment by pityalvarez** [comment]
I'm using 1.16.5 that's why, I really need it. There's no crash log, it just doesn't do anything, and it's true - enabled

**Comment by Motschen** [comment]
If the 2.0.0 version works for you, just stick with it.
I'll close this issue since I don't support 1.16 anymore.
