### ISSUE TITLE
Crashes with Sodium 0.4.9

### ISSUE THREAD

**Issue by HhiPyrene** [TeamMidnightDust/CullLeaves#35]
Game crash when loading a world.
[crash-2023-02-07_18.02.41-client.txt](https://github.com/TeamMidnightDust/CullLeaves/files/10673847/crash-2023-02-07_18.02.41-client.txt)
[latest.log](https://github.com/TeamMidnightDust/CullLeaves/files/10673848/latest.log)

**Comment by orbittwz** [comment]
adding to this, Iris 1.5.2 for Sodium 0.4.9 just got released, crashed when loading a save game, and also when starting a new game just to make sure it's not a problem with previous saves.
https://mclo.gs/dTwqzfc
https://mclo.gs/tQmFSk3

**the game and either saves works when this mod is disabled**

please check this...

**Comment by Celesian** [comment]
can also confirm
