### ISSUE TITLE
[Feature Request] An option to make leaf rendering more similar to Optifine's Smart Leaves

### ISSUE THREAD

**Issue by Abbanon** [TeamMidnightDust/CullLeaves#4]
So for context, this is how Optifine's **Smart Leaves** render:
![o42LU40](https://user-images.githubusercontent.com/37251822/104598123-33b1fe80-5644-11eb-8c25-a90e74fe6a0c.png)
Notice how with Optifine, you can still see the back/sides/top/bottom of the leaves while the center is empty.

And this is how **Cull Leaves** currently renders:
![2021-01-14_07 57 39](https://user-images.githubusercontent.com/37251822/104598201-49272880-5644-11eb-82a4-70a0179938e1.png)
Notice how it only renders the sides directly facing you, and you can't see the back/sides/top/bottom. While very effective with increasing performance, it doesn't look all too great on its own.

So I ask you; Would it be at all possible to add an option for Cull Leaves that will visually resemble OF's Smart Leaves rendering?
Where you can still see all exterior sides of leaf blocks, but not the inside where they connect?

**Comment by Motschen** [comment]
I got it working with just a resourcepack! Enjoy ;)
[Smart-Leaves-1.0-§31.16+§o.zip](https://github.com/TeamMidnightDust/CullLeaves/files/5815049/Smart-Leaves-1.0-.31.16%2B.o.zip)

**Comment by Motschen** [comment]
Included as an optional resourcepack in v2.0.0 :)
