### ISSUE TITLE
Incompatible with Sodium 0.5.0

### ISSUE THREAD

**Issue by Turjoy9** [TeamMidnightDust/CullLeaves#43]
Recently Sodium dropped a huge update with LOTS of internal changes. With this update Cull Leaves 3.1.0 became unusable with sodium 0.5.0.

Attaching crash logs and additional info for the developer to help identify the issue and fix it.

Game Version:  1.20.1
Fabric Loader Version: 0.14.21
Mods Used:  `Cull Leaves 3.1.0, Fabric API 0.86.1+1.20.1, Sodium 1.20.1-0.5.0`

Steps to recreate the crash:

- Install Fabric.
- Put mentioned mods in the mods folder
- Open the game
- Join a server

Full Client Log:   https://mclo.gs/8VKHRck
Crash Report:   https://mclo.gs/6gYpzfg

**Comment by Hansynily** [comment]
Will wait too
https://mclo.gs/HYQiNl6

**Comment by LokeYourC3PH** [comment]
Came here to say this. There's like three mods currently causing this for me: Cauldron Dyeing, Fluid Void Fading and Cull Leaves.

**Comment by pingouyn** [comment]
Same as OP.  Doesn't work with sodium 0.5.0, making the new sodium a no go for me till CullLeaves is updated and compatible with sodium 0.5.0.

**Comment by Motschen** [comment]
I just tried it with Sodium 0.5.1 and it seems like this incompatibility doesn't occur anymore, can anyone confirm?

**Comment by pingouyn** [comment]
I can confirm CullLeaves does not do anything in terms of leaves culling with both sodium 0.5.0 and 0.5.1
