### ISSUE TITLE
Adding mods has no effect

### ISSUE THREAD

**Issue by zc1108aaa** [TeamMidnightDust/CullLeaves#50]
![image](https://github.com/TeamMidnightDust/CullLeaves/assets/155424398/5e5f2ff4-1ce0-4ae3-bc69-a05022cd1708)
Which mod is not compatible
[latest.log](https://github.com/TeamMidnightDust/CullLeaves/files/15463342/latest.log)

**Comment by Motschen** [comment]
This works as intended. The mod has no visible effect with fast leaves, but will still boost the performance.
For the "Smart Leaves" effect, set leaves quality to fancy.
