### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [TeamMidnightDust/CullLeaves#54]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by Motschen** [comment]
Feel free to include the mod in any modpack you like :)
Also, you usually can assume any mod can be included in modpacks, unless stated otherwise in the description.
